### ISSUE TITLE
Potential Wine Issue - Server Not Starting

### ISSUE THREAD

**Issue by paytah232** [jammsen/docker-the-forest-dedicated-server#13]
Hi! I'm really excited to get a dedicated server running for my friends and I, so it would be great trying to get you to help me with this. I have uploaded the log file of the system setup I created. Is seems to have had trouble either getting the game as the main issue I see is: `wine: cannot find '/theforest/TheForestDedicatedServer.exe'`. I'll do what I can to run tests etc so hopefully we can resolve the issue for myself, and other future users.
I am running on a synology nas, using docker.

I set up volume links as below:
![image](https://user-images.githubusercontent.com/44075588/115882559-35376200-a490-11eb-8e9b-b6adb34546d4.png)

Env Vars:
![image](https://user-images.githubusercontent.com/44075588/115882586-3cf70680-a490-11eb-9bb0-5d77bfd2d7c6.png)

Port Settings (couldn't use standard as I'm already using them elsewhere.
![image](https://user-images.githubusercontent.com/44075588/115882776-70399580-a490-11eb-965e-511452c31c77.png)

Log:
[Pugno-NAS_The_Forest_Server.zip](https://github.com/jammsen/docker-the-forest-dedicated-server/files/6365796/Pugno-NAS_The_Forest_Server.zip)

**Comment by jammsen** [comment]
Hey i cant reproduce that and the log seems fairly okay to me. Im unsure on how to help you. But did you try to reprovision my image again and deleting all image caches before that? 

Alternative: If my image isnt working for you i can highly recommand the images of ich777 ( https://hub.docker.com/r/ich777/steamcmd Tag 7dtd ) which is more focussed around unraid but could be working for you or you do try Dids's image ( https://hub.docker.com/r/didstopia/7dtd-server )

Please let me know if you get it working.

**Comment by paytah232** [comment]
To me it seems like it isn't downloading the forest game files... I could be wrong but on a fresh install I got the same errors so not sure. Anything else I can do to try?

**Comment by paytah232** [comment]
Okay so I tried a fresh docker install without mounting any folders and it is installing the forest. When I mount /theforest and /steamcmd to a volume on launch, package installation fails I think. Know any reason why?

**Comment by jammsen** [comment]
Possible permission issues? Check chmod/chown for rights and user rights with Docker. Do you run rootless on your system or native with root user?

**Comment by paytah232** [comment]
Okay, so I copied theforest and steamcmd folders from the working container to mine with the mapped ports and I have made some progress. It seems the server boots up, except it is running the wrong IP. I guess the config file is being ignored... is there a fix for that?

[log.zip](https://github.com/jammsen/docker-the-forest-dedicated-server/files/6369721/log.zip)

**Comment by paytah232** [comment]
> Possible permission issues? Check chmod/chown for rights and user rights with Docker. Do you run rootless on your system or native with root user?

Permissions should be fine. I run the container with administrator PUID and GUID, so I woiuldn't think that is the issue.

**Comment by jammsen** [comment]
>  It seems the server boots up, except it is running the wrong IP. I guess the config file is being ignored... is there a fix for that?

That should not happen, the servermanager sets the IP itself:
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L71

**Comment by jammsen** [comment]
Also please if you want to provide logs post on pastebin. But only logs wont help to find out whats mounted and what not.

**Comment by paytah232** [comment]
Okay sure. What do you need me to provide?

**Comment by jammsen** [comment]
Logs + docker inspect [containerid] + ls -al of your folders for permissions + infos about how your docker runs on your system.

**Comment by paytah232** [comment]
Docker Inspect > log : https://pastebin.com/yxRsUSqx
Latest Log from docker container: https://pastebin.com/YcY9HZj5
LS -al from multiple locations: https://pastebin.com/0Q9czz03

Hi @jammsen, find the pastebin links of all the logs I could get for you. The docker just runs as a service on my Synology NAS as far as I know. I have used docker containers to host ARK and Minecraft servers in the past with no issues, there just seems to be something wrong here. Like I said, it seems like the server ignores the config I give it, because otherwise it might be able to work. Thoughts?

**Comment by paytah232** [comment]
These are the processes running under the docker container if it helps: it looks like it's pointing itself to where the config file it, but it definitely doesn't return the correct IP that it should be hosting from (i.e. my NAS DDNS)
![image](https://user-images.githubusercontent.com/44075588/115978157-f0f7af00-a5c0-11eb-8599-d846369eea55.png)

**Comment by paytah232** [comment]
@jammsen so I booted it again now, and the server is runnable and I can connect to it, but it has all the default server settings. The hostname is the jammsen-generated and the save game does not save to the correct location. Hopefully we can figure it out, because it is so close to working.

**Comment by jammsen** [comment]
A few weird things i see are:
- Please never use spaces in volume mounts, this can make so many problems, just use the-forest/the.forest/the_forest or so - /volume1/docker/The Forest/steamcmd:/steamcmd:rw
- The IP seems to change while the script tries to start - You configure ip address as 172.17.0.7 but your host IP seens to be 172.17.0.6 - Try to change that manually, the ip is only setup be fresh install
- Stop the container, look inside the "/theforest/config/config.cfg" and try to change some things up and start it again - This config is only once copied from "/server.cfg.example" to "/theforest/config/config.cfg" when the server can find the exe of the server, meaning in the volume is empty and a fresh install is needed, otherwhise you can config the server in the earlier mentioned config.
- The docker-log is a compilaton of errors and working states, without any context, a clean log with only latest data would help a lot more
- A "cat /theforest/config/config.cfg" would be helpful and also a "ip a" from the running container
- From what i can see the server doesnt ignores the config why would you assume that?

**Comment by paytah232** [comment]
- Fixed. Changed to /docker/Forest/steamcmd etc.
- I never configure the IP to this. I set my IP via the config file to be my DDNS server IP of Pugno-NAS.synology.me; so I this is why I think the config file is being ignored, as I state this in the config file.
- I have the server name set to "The Banging Forest" (a discord name offshoot) and yet it configures with the default jammsen..... (it also does not save to the right location, and I cannot import save files to that location.
- The log I gave you was from a server start today with no other entries;I do not know how to provide you with a better log. If you do, please tell me how and I will provide it to you.
- "ip a" does not work from the bash terminal of the server
- As far as the config goes, I have provided it at the following paste, minus admin passwords etc.:  https://pastebin.com/kxPymNBf
- I believe the config doesn't work because it does not save the game to the given location, which means I can not load in an existing save file to continue from that. When I joined the server and started and saved a game, no save file appeared in the given location.
even with the config file as above, I only see this in the game:
![image](https://user-images.githubusercontent.com/44075588/115993688-3b0b7f80-a617-11eb-9328-6c3b0c053568.png)
(Note i changed the server name to "The_Banging_Forest", and still I can only see the attached image, and cannot access the save files.

**Comment by paytah232** [comment]
![image](https://user-images.githubusercontent.com/44075588/115993775-a8b7ab80-a617-11eb-858a-137bfc9cd01f.png)
The server has the above IP, which I think is set by your code and only accessible by my LAN, even though I choose to connect over internet. I assume that this server is the one I am running, as when I shut mine down it is no longer accessible, and in my server I have a different name and password in the config file, and this container will accept any password.

**Comment by jammsen** [comment]
Do you see anything wrong when "read" the instructions and compare to what you have done? :)
// Server IP address - Note: If you have a router, this address is the internal address, and you need to configure ports forwarding
serverIP pugno-nas.synology.me 

You have to provide the internal IP of the docker container not external, also in your docker inspect you do not mount the ports to the host 
`
            "Ports": {
                "27015/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32772"
                    }
                ],
                "27015/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32771"
                    }
                ],
                "27016/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32771"
                    }
                ],
                "27016/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32770"
                    }
                ],
                "8766/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32775"
                    }
                ],
                "8766/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32772"
                    }
                ]
            },
`
Compare the settings to the docker-compose.yml or alternatively try using Dids's or ich777 container and see if that works better for you, i kinda get a feeling you did something wrong from the get go and we chasing an error that might not be there aka a ghost.

**Comment by paytah232** [comment]
So I still don't understand how it can be something I have done wrong... I have set up several server dockers in the same way and they work fine. Same port and volume mapping method, and I adjust the game ports in the config file and it all works, it's just here the config file does not seem to be getting loaded; i.e. why is the server not named what I named it; why doesn't it have my passwords. I don't see how some setting I have could possibly cause that.

I there a way in your code that I can hard code the server parameters, just to confirm that it is indeed an issue with the config file not loading?

**Comment by paytah232** [comment]
I also don't understand how I can use Did's or ich777 containers when they don't use the forest explicitly. If you know how I can make that work, if you can provide instructions I will try that also.

**Comment by jammsen** [comment]
Regarding your question "doing wrong"
Im not saying you did something wrong, just that your config and the settings are weird, my image has over 10k++ pulls and many ppl how are using it, i never once experienced the errors you had, which cant traced any where really. Im not trying to be mean to you, just beeing honest here, no clue what i can otherwhise do to help you out.

Regarding your quesion "hardcoding"
You can fork my image and hardcode in anything you want, i dont have your setup so i cant reproduce anything here, so i wont change my image according to that.

Regarding your question "ich777 and Dids's"
Dids and ich777 do provide 7dtd server, you just could have googled it ... try it out
google: docker hub didstopia 7dtd-server
google: docker hub ich777 steamcmd 7dtd

**Comment by paytah232** [comment]
Given my port and volume setup, could you generate a docker-compose file for me to try, that way the settings are controlled? Will that work?

And I know what they are, I just don't see how they'll help when I'm running The Forest, not 7dtd...

**Comment by jammsen** [comment]
Sorry, it was a typo i meant the-forest not 7dtd ... kinda tought you get my point .... anyway i googled it for you  ... try these out .......
https://hub.docker.com/r/didstopia/theforest-server
https://hub.docker.com/layers/ich777/steamcmd/theforest/images/sha256-9005fe6da930f14113cd2d984a0b2c95b3745cda4700bc7b98bdb9f256d2cd97?context=explore

**Comment by jammsen** [comment]
Can this issue be closed?

**Comment by paytah232** [comment]
I tried one of the other docker and the setup worked but I didn't find it online. I guess if you can't help anymore you can close.
