### ISSUE TITLE
Control the server?

### ISSUE THREAD

**Issue by exetico** [jammsen/docker-the-forest-dedicated-server#15]
Hi,

I'm very used to Docker and contained software, too. 

Are the any way of controlling the server - to force save, "soft shutdown" and other things, too? I've not found any documentation related to it.

And oh; Thanks for creating the wrapper with the needed tools. It worked out of the box in my server, so that's great!

**Comment by jammsen** [comment]
Hey i dont think there is something similar than RCON or TELNET for forcing saving. But  "when" i remember right, if you stop the server via supervisord its basically like doing CRTL+C on Windows and it "should" save before exiting. Its the same i hope with supervisord and the SIG-Codes. I never found any documentation about that dedicated-server, its all only community driven :/

When you look [here](https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/etc/supervisor/conf.d/theforest.conf) and [here](https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L24) you see i already prepared the server for some auto-updating, i just dont have the time right now to finish and test it adequatly.

**Comment by exetico** [comment]
Thank you for the insights. It's sad that it's lacking official support. But that's not on you, for sure 😁!
