### ISSUE TITLE
Patch version out of date

### ISSUE THREAD

**Issue by ReaperZa** [jammsen/docker-the-forest-dedicated-server#17]
Firstly. I want to say thanks for this!! Been looking to run this is a container for so long.

I'm running into a issue where it says that the patch version of the server is different to the one in the game, I ran the steamcmd update but still doesn't seem to fix it. Any ideas?

**Comment by jammsen** [comment]
Hey @ReaperZa 
im not sure i can follow your problem, because it never happend to me, can you please provide some logs and screenshots?
Also a "docker version" and directory listing with "ls -R" for your files inside the server would be nice.

**Comment by ReaperZa** [comment]
Hi @jammsen 

Seems I resolved the error on my side. My steam 'key' expired... so renewed it and retested. All working fine now.
