### ISSUE TITLE
Server is running but i cannot connect

### ISSUE THREAD

**Issue by TroyKomodo** [jammsen/docker-the-forest-dedicated-server#2]

**Comment by TroyKomodo** [comment]
Server is not responding

**Comment by Goundski** [comment]
Same issue here. get "CONNECTING CLIENT" screen and that is where it stays forever.

**Comment by TroyKomodo** [comment]
I suspect its got something to do with that its running in a docker and its not forwarding the ports as it its running on a different ip then the server.

**Comment by Goundski** [comment]
I doubt that it is the ports as I see the service broadcasting onto the net as my steam can find it. But when I connect it just stays in that state. If the ports was blocked or unavailable then steam would also not find the server.

**Comment by TroyKomodo** [comment]
I reverted to using the original guide for a forest server and it seems to
be working fine

**Comment by jammsen** [comment]
First of let me say im so sorry, but i never got any notification on open issues for this. 

Is this still a problem?

**Comment by Brramble** [comment]
> First of let me say im so sorry, but i never got any notification on open issues for this.
> 
> Is this still a problem?

I've just this second found this issue and I can say I am still having the same problem!

**Comment by jammsen** [comment]
I did a complete overhaul of the server, could please try again now?
Also if its still persist, can you explain your network config please?
