### ISSUE TITLE
`server.cfg.example` Not Applied

### ISSUE THREAD

**Issue by aurexav** [jammsen/docker-the-forest-dedicated-server#22]
Even in a fresh new install. It still uses the default values.

```
Starting dedicated server
Dedicated server info:
 IP:172.17.0.2, steamPort:8766, gamePort:27015, queryPort:27016
 players:8, admin password:'no', password:'no', autosave interval:30
Game setup: Standard Multiplayer Server, Continue Normal game, slot Slot1
```

**Comment by jammsen** [comment]
Of course it uses the default values, thats why the default config example for fresh installs exists. Its working as intended.
You either change the default config and do a fresh install or you do a fresh install, stop the server, look into mounts and change the generated config.
