### ISSUE TITLE
"Failed to connect to Steam"

### ISSUE THREAD

**Issue by leifbln** [jammsen/docker-the-forest-dedicated-server#24]
Hi Jammsen, thank you very much for your effort here. 

I'm trying to get your solution working on my Debian 11 with Docker.  

Most of the installation is going through pretty fine but there is an exception thrown after downloading the resources etc.

```
Steam Manager Started.
0108:fixme:ntdll:EtwEventRegister ({f72b578f-cae9-556a-01dc-b94f14b3cbd9}, 000000013F001100, 000000013F05B018, 000000013F05B038) stub.
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504BE, 13) stub
0108:fixme:ntdll:EtwEventRegister ({66f0a0b9-f747-5080-bdb9-4974c990ecd2}, 000000013F001100, 000000013F05B050, 000000013F05B070) stub.
0108:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000013F0504DC, 19) stub
019c:fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
019c:fixme:wbemprox:client_security_SetBlanket 000000000422FD50, 000000000F72FBB0, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
019c:fixme:wbemprox:client_security_Release 000000000422FD50
0188:fixme:iphlpapi:NotifyAddrChange (Handle 0x26050410, overlapped 0x26050418): stub
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
019c:fixme:wbemprox:enum_class_object_Next timeout not supported
0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
0060:fixme:mountmgr:query_property Faking StorageDeviceProperty data
0060:fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled
Setting breakpad minidump AppID = 242760
GameServer init success. Port: 27015
Set a Logon
dbus[212]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

 D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00007F7CD2B0FCE1 (thread 0060), starting debugger...
0188:fixme:winsock:WS_setsockopt SO_SNDBUF ignoring request to disable send buffering
0184:fixme:server:invoke_system_apc syscall frame changed in APC function, frame (nil), saved_frame 0x280dfa18.
Failed to connect to Steam
```

Debian Machine is having full Internet Access and also Port Forwarding is already setup. I'm not that deep in wine to find out what is going wrong here. Found several times pretty similar Logs but was not able to read the solution for that. 

Tried both Bash Commands you provided with my created Steam Token.

Would  be great if you could assist me to get this running.

**Comment by jammsen** [comment]
I get sometimes the same result, that Steam couldnt connect, thats sometimes an api-endpoint which does not respond or when i to often start the container in rapid succession in a small time window, i just try it after some time again and it works. No idea what the problem is.

**Comment by leifbln** [comment]
Thanks for your reply, any chance to check some log files for that? 

Also what is the best way to cleanup properly before giving it a retry?

**Comment by jammsen** [comment]
> Thanks for your reply, any chance to check some log files for that?

What do you mean?

> Also what is the best way to cleanup properly before giving it a retry?

For cleanup, just remove all files in the host directory and do everything fresh.
For retry, just stop the container for some time, a few hours and restart it again and look whats happening.
What Steam internally does to say failed to connect, well i have no idea and to my knowledge there isnt a log to lookup.

**Comment by leifbln** [comment]
> What do you mean?

Not sure, maybe some Installation log to see where exactly in the process it stops. Tried it over the day today with some time in between but didn't had success.

Will maybe do additionaly some tcpdump to check what happens on the network layer. 

Just to ensure that there is no issue with debian, could you please let me know on which platform you installed the docker container? 

Thanks, will let you know as soon i've digged more into it.

**Comment by jammsen** [comment]
> Just to ensure that there is no issue with debian, could you please let me know on which platform you installed the docker container?

Im using 3 Systems for testing of docker container development, regarding security i wont share any details, but i can give a rough estimate what the base of my distributions are:
1 Slackware-based, 2 Debian-based - most of them are basically up-to-date and are running Docker 20.X.Y

**Comment by leifbln** [comment]
Tried several things, analysis and several platforms, as well simple container stations but had no success. TCPdump was showing me broken TCP/TLS connection to Steam, but I couldnt find the cause for that. 

Will try to find another way to setup my dedicated Server for now. Thanks anyway!
