### ISSUE TITLE
(another) wine: chdir to /winedata/WINE64 : No such file or directory

### ISSUE THREAD

**Issue by ProjectPatatoe** [jammsen/docker-the-forest-dedicated-server#25]
Started it up, downloaded and ran `docker-compose up` to test. Everything seemed to work despite "failed to connect to steam". Got into the game and realized I needed to change some configs for ports, name, etc.

Pressed Ctrl+C to stop
made changes to config
`docker-compose up` and now the errors:
```
wine: chdir to /winedata/WINE64 : No such file or directory
wine: chdir to /winedata/WINE64 : No such file or directory
```

**Comment by brandoncamenisch** [comment]
Same for me 😿 I run a few of these servers and it was on all of them. 

I was able to start a server with a totally fresh install and it worked ok but as soon as I restarted the container this pops up 😫 

Trying to resolve but IDK how this 🍷 stuff works quite yet.

**Comment by jammsen** [comment]
Hey, sorry for the delay, im really busy.
Yeah i dont really know why restart doesnt work and i have not enough time at hand now to debug it. This will take some time.
Workaround: Just keep your config and saves and do a fresh install every time, that should work just fine.

**Comment by jammsen** [comment]
Problem should be fixed.
