### ISSUE TITLE
Server is running a different patch release

### ISSUE THREAD

**Issue by mr-gosh** [jammsen/docker-the-forest-dedicated-server#29]
"Server is running a different patch release" & "Failed to connect to Steam"

So the second issue is exactly like in #24 - but the more interesting bug is that when i try to connect (via lan) it says that the server is running a diferent patch release of the game and is not compatible:
![Bildschirmfoto von 2022-05-15 22-50-04](https://user-images.githubusercontent.com/3028703/168493236-d7a6fa24-50fa-4b77-8aa6-d5587f4c7ac7.png)

**Comment by Chillidaddy** [comment]
Had the same problem. 
Rebuilding the image from his Dockerfile fixed the problem.

**Comment by jammsen** [comment]
At the moment im ill, i might take a look at the weekend, no promises.

**Comment by mr-gosh** [comment]
@jammsen  Get well soon
@Chillidaddy do you have instructions for building somewhere?

**Comment by jammsen** [comment]
Try the `docker-build-and-run.sh`  -> [docker-build-and-run.sh](https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/docker-build-and-run.sh)?

**Comment by MOHMOBILE** [comment]
After literally hours of trial & error, I found out, that (at least for me) the environment variable that you set in the docker container adds two hashtags to the beginning and end of your server account token in the **config.cfg**. After I removed them, the server started normally and I was able to login to the server.
I hope this short comment can help anyone having the same issue.

Thank you @jammsen for your engagement in this project! It's very great!

**Comment by McNobby** [comment]
I did remove the hastags @MOHMOBILE mentioned but for me, that hasn't helped.. I think im having a similar issue with the version mismatch or possibliy something else. In the image below i added the server in the steam server favourites as it's hosted in a vps, and the player count is 0/0 which i think could be related.

For all i know there is a different issue for me but for now will be waiting for @jammsen to get well :)

![image](https://user-images.githubusercontent.com/76711087/169902768-670bec1d-345e-42f9-b4df-a9fbe02c7132.png)

**Comment by jammsen** [comment]
Hey guys, it seems like the code is okay, but the Docker Hub version wasnt published from my private testing repo to the public. Sorry for that, could you please try out this version and give me feedback within 48h? 
https://hub.docker.com/layers/the-forest-dedicated-server/jammsen/the-forest-dedicated-server/323de463/images/sha256-4065170ca2d234d4767107afbd0b531cb674d6a96a80c9b3cb4ad6e68b10eae6?context=explore

**Comment by jammsen** [comment]
The build is working for me, but im missing your feedack, i will wait another bit and then tag this build with latest, if nothing comes up.

**Comment by jammsen** [comment]
The image was published under jammsen/the-forest-dedicated-server:latest

Closing this issue, due to inactivity.

Also thanks to @mr-gosh and @MOHMOBILE for blessings and beeing very nice 👍

**Comment by mr-gosh** [comment]
i am able to test the image this evening
