### ISSUE TITLE
Server setting "difficulty Peaceful" is not used by server

### ISSUE THREAD

**Issue by Digifreakske** [jammsen/docker-the-forest-dedicated-server#3]
Dear,
I've set the difficulty to "Peaceful" in the config.cfg file but we still see 'enemies' in the server.

I've checked the config file from within the docker (option is set correctly set).
I've checked how the theforestDS process is started and it clearly points to the config.cfg file.

Not sure if you can do anything about it (or know more about it).
Have you notices the same behaviour?

Regards,
Frederik

**Comment by jammsen** [comment]
First of let me say im so sorry, but i never got any notification on open issues for this. 

I never used that option, can you enter the container and "cat ..." the config file to check if the option is still set?
