### ISSUE TITLE
"WARNING: If you dont do Step 1 and 2 your server can/will not save!"

### ISSUE THREAD

**Issue by Xenograph** [jammsen/docker-the-forest-dedicated-server#35]
Hi! Quick question about this warning in the README for the repo:

`WARNING: If you dont do Step 1 and 2 your server can/will not save!`

This implies that you need to set `SERVER_STEAM_ACCOUNT_TOKEN` AKA `serverSteamAccount` in order for the game to save. But is this really true? I run the dedicated server normally on Windows (without using this Docker image), and do not set `serverSteamAccount`. But the game seems to save just fine still. Is this warning in the README perhaps misleading, or is there some reason that it is required in this case?

**Comment by jammsen** [comment]
No its not misleading at all, there is a reason, to what i write.

The information is from the multiple wikis ( like https://theforest.fandom.com/wiki/Dedicated_Servers ) and experience over the years, with a lot of save related problems. Yes, there is some documentation, where it says you can leave it blank and it will do it "anonymous" ( https://steamcommunity.com/sharedfiles/filedetails/?id=907906289 ). So yeah you can also leave it blank and it "should" do all that. Its all a "should". 

I found if i leave it blank sometimes servers ... 
- wont save
- wont save right and buildings over time despawn 
- cant connect to the master server and get inserted in the list, so users cant join

All that kind of stuff.

**Comment by jammsen** [comment]
Closed due to inactivity
