### ISSUE TITLE
Errors on start

### ISSUE THREAD

**Issue by perpetualconfusion** [jammsen/docker-the-forest-dedicated-server#37]
Using the latest image & the supplied docker compose. The error appears to be within the image itself.

- gzip: stdin: unexpected end of file
- tar: Child returned status 1
- tar: Error is not recoverable: exiting now
- bash: /steamcmd/steamcmd.sh: No such file or directory
- wine: failed to open "/theforest/TheForestDedicatedServer.exe": c0000135

I have also tried an older version tag. Same issue. 

Ideas?

**Comment by Tnze** [comment]
same problem

**Comment by jammsen** [comment]
Oh, i will look into that, thanks for letting me know.

**Comment by jammsen** [comment]
So using the live image works just fine for me:
```bash
docker run --rm -i -t -e 'SERVER_STEAM_ACCOUNT_TOKEN=generated-token-here' -p 8766:8766/tcp -p 8766:8766/udp -p 27015:27015/tcp -p 27015:27015/udp -p 27016:27016/tcp -p 27016:27016/udp --name the-forest-dedicated-server jammsen/the-forest-dedicated-server:latest
```
I will try local building next.

**Comment by jammsen** [comment]
Local building with the scripts worked too:
```bash
One player leave dedicated server. No players at the server.
Unloading 7 Unused Serialized files (Serialized files now loaded: 1)
Saving 32 trees that were cut down
Game saved
```

Can you describe your problems more?
Where is that log from?
When does it occure?
What version of Docker do you use? (Rootless or Rootful?)
What OS?

**Comment by Tnze** [comment]
Which platform do you test on? x86 or x64?

**Comment by Tnze** [comment]
I test it with the same command
```bash
docker run --rm -i -t -e 'SERVER_STEAM_ACCOUNT_TOKEN=anonymous' -p 8766:8766/tcp -p 8766:8766/udp -p 27015:27015/tcp -p 27015:27015/udp -p 27016:27016/tcp -p 27016:27016/udp -v /srv/tfds/steamcmd:/steamcmd -v /srv/tfds/game:/theforest --name the-forest-dedicated-server jammsen/the-forest-dedicated-server:latest
```

It works now, which is wired. This issue could be closed.

**Comment by jammsen** [comment]
> Which platform do you test on? x86 or x64?

I tested it on Windows and Debian/Ubuntu Linux, so basically x64 & x86.


> It works now, which is wired. This issue could be closed.

Okay, feel free to open a new issue if you got any problems.
