### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by DanielTezolin** [jammsen/docker-the-forest-dedicated-server#39]
Hello everything is fine?

I'm having trouble starting
Docker version 1.13.1, build 7d71120/1.13.1
I'm running on a CentOs 7 server

This is the log output:

```
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
[  0%] Checking for available updates...
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
CWorkThreadPool::StartWorkThread: Thread creation failed.
```
Have you ever had a similar problem?

Thank you very much in advance.

**Comment by jammsen** [comment]
Hey @DanielTezolin 
No i have had that never before.
Could you please explain your setup?
Also how you start the container?
Ive never heard of a Docker Version 1.13.1 i only know 19.XX and 20.10.XX
I need more information to even consider recreating things.

**Comment by DanielTezolin** [comment]
Hello,

with your answer I saw that the docker setup.sh that I made is installing a very old version, causing many errors that I have been facing.

I installed the latest version of docker and it worked perfectly.
It's running on acentos 7 virtual machine on proxmox.

Thank you so much for giving me this light lol

**Comment by jammsen** [comment]
No problem  @DanielTezolin cheers, have a nice weekend 👍
