### ISSUE TITLE
constructions have disappeared

### ISSUE THREAD

**Issue by Ho2x** [jammsen/docker-the-forest-dedicated-server#4]
Hello,
everything works fine but I have a problem.
I played all day yesterday and unfortunately, I realize that all my constructions have disappeared.
even after a server restart these are still not there.
An idea ?
 thank you

**Comment by Pidbid** [comment]
Hello,
May be you can restart the server.

**Comment by jammsen** [comment]
First of let me say im so sorry, but i never got any notification on open issues for this. 

That issue was already there when i did create this docker-based container, i never found a fix for it. It might have something to do with Wine and the Severcore. It always helped me to restart the server.

**Comment by jammsen** [comment]
I did do a rework of the server, please try if this still happens.

**Comment by jammsen** [comment]
Closed for inactivity.
