### ISSUE TITLE
Two separate docker instances

### ISSUE THREAD

**Issue by themightylc** [jammsen/docker-the-forest-dedicated-server#40]
Thank you @themightylc 

@jammsen I was finally able to make it work. How would you recommend I it if I want to have 2 servers running in one machine? I tried just creating a new container with different docker ports but now the old server cannot be found in game, only the newly created one

_Originally posted by @jcads in https://github.com/jammsen/docker-the-forest-dedicated-server/issues/38#issuecomment-1354329720_

**Comment by themightylc** [comment]
My guess would be that the problem there lies with the steam token and you need a second, separate steam-token for the game, if this is possible (which i think it is).
Steam uses this token to identify servers and i would naturally assume that it needs to be unique for each server. :)

**Comment by jammsen** [comment]
Yeah of course, just like in the readme explain. You should try that.

**Comment by jcads** [comment]
Thank you @themightylc that worked for me

**Comment by themightylc** [comment]
wonderful. :)
