### ISSUE TITLE
predefine config.cfg values as environment variables in the docker compose.

### ISSUE THREAD

**Issue by njakes** [jammsen/docker-the-forest-dedicated-server#43]
Just as the title says, I am wondering if this is at all possible.

**Comment by njakes** [comment]
I am closing issue due to the answer being mentioned in another issue. https://github.com/jammsen/docker-the-forest-dedicated-server/issues/42

**Comment by jammsen** [comment]
Hey @njakes 
i didnt see this issue before you closed it. Also i didnt say no to your request. I only said "I dont plan to extend the run command or enviroment-vars for any configline" with focus on "any/every configline" and in combination to docker run.

Im open to at least talk about this and to hear you and figure out what exactly do you have in mind.

Also are you aware that the server-manager only creates the config-file once with initial settings at the first installation stage? It doesnt auto-merge values every run of the gameserver to the config file. Even the IP works that way, see here:
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L57-L67

**Comment by jammsen** [comment]
Sad to hear nothing for improvement of this image, well then i guess i close this.

**Comment by njakes** [comment]
Ahh yes, I'm sorry about that, life got busy for me.  Thank you again for such amazing work. You may leave this issue closed. Things work great already.
