### ISSUE TITLE
Enhancement: Update on start

### ISSUE THREAD

**Issue by jacoknapp** [jammsen/docker-the-forest-dedicated-server#49]
Enhancement request: Set the update on start environment variable here as well, similar to how it was done in sons of the forest.  I'm not sure this is going to be a real concern, because i don't know how often if at all the dev is updating the-forest anymore, but it would be a nice to have

**Comment by jacoknapp** [comment]
I can work on this and submit a PR similar to how you have it set up in sotf sometime hopefully this weekend (though may be next week) Just was putting it here to track it so i don't forget, or if i just missed something in the code where it is already working.

**Comment by jammsen** [comment]
Hey @jacoknapp 
thanks for the input - Im gonna do it myself when i have time for it, dont bother 😄 I have to do all the testing anyways before i can release a new image.

**Comment by jammsen** [comment]
Hey @jacoknapp - Sorry i just dont find the time to do it, if you want go ahead and submit a PR if you like, i will do the testing for sure and update the other stuff if needed.

Very sorry for promising something and then dont deliver it 😢

**Comment by jacoknapp** [comment]
No problem, i can do it. You have the work already completed with sons of the forest, so i can just clone that and it saves me reversing engineering time figuring out how everything with steamcmd runs. Ill verify the command runs, but will only do some limited testing on my side, if you want to verify.
