### ISSUE TITLE
I want to revive kevin, but where is my save file?

### ISSUE THREAD

**Issue by Junnyjun** [jammsen/docker-the-forest-dedicated-server#52]
I want to know how to install additional mods.

**Comment by jammsen** [comment]
In The Forest there is no Kevin.
Savefile: https://savelocation.net/the-forest
Mods: https://theforest.fandom.com/wiki/Mods

**Comment by jammsen** [comment]
Save-Game inside Docker:
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/dc33896e091008e0ad39b85146f5406a3f975161/usr/bin/servermanager.sh#L81C90-L81C106

**Comment by Junnyjun** [comment]
> In The Forest there is no Kevin. Savefile: https://savelocation.net/the-forest Mods: https://theforest.fandom.com/wiki/Mods

There seems to be a misunderstanding.
Is it possible to revive NPC that help me get resources?

**Comment by Junnyjun** [comment]
> Save-Game inside Docker: https://github.com/jammsen/docker-the-forest-dedicated-server/blob/dc33896e091008e0ad39b85146f5406a3f975161/usr/bin/servermanager.sh#L81C90-L81C106

I'm in the wrong place, sorry
