### ISSUE TITLE
A more detailed step by step guideline needed

### ISSUE THREAD

**Issue by heusmich** [jammsen/docker-the-forest-dedicated-server#53]
Hi,

A question from my side, would it be possible that you provide a more detailed step by step guideline for the installation and activation of this SotF Docker container?
I don´t really have a lot of knowledge in Docker (and I also think a lot of others also don´t have) and it would help us to install and use your Docker file.

Best regards
heusmich

**Comment by jammsen** [comment]
Hello @heusmich 
( see https://github.com/jammsen/docker-the-forest-dedicated-server#docker---sons-of-the-forest-dedicated-server )
this is the repo for The-Forest not Sons-of-the-Forest, thats here: https://github.com/jammsen/docker-sons-of-the-forest-dedicated-server

Feel free to open a issue there and include what you are missing in the guide and give me details on that, otherwhise im nowhere smarter on what you are missing/not getting.
