### ISSUE TITLE
Where does this docker container stores the savefiles for the server?

### ISSUE THREAD

**Issue by krowisoft** [jammsen/docker-the-forest-dedicated-server#54]
Since this is not a windows system and and does not have an %appdata% folder, where is the file getting stored? Does docker automatically stores it somewhere else?

**Comment by jammsen** [comment]
Hello @krowisoft 

as you can see here in the start script it will use a custom config and savepath: 
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/usr/bin/servermanager.sh#L81 -> /theforest/saves
This will map to whatever you setup im Docker-Compose according to the readme:
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/master/README.md - Docker-Compose-Section

So youre full path should be known to you if you read this.

**Comment by krowisoft** [comment]
Thank you very much. I found it.
