### ISSUE TITLE
Wine Debian Bullseye Docker Image No Longer Exists

### ISSUE THREAD

**Issue by JamesComo44** [jammsen/docker-the-forest-dedicated-server#60]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Unable to build the docker image.
```
[+] Building 0.2s (2/2) FINISHED                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.04kB                                                                             0.0s
 => ERROR [internal] load metadata for docker.io/jammsen/base:wine-stable-debian-bullseye                          0.2s
------
 > [internal] load metadata for docker.io/jammsen/base:wine-stable-debian-bullseye:
------
Dockerfile:1
--------------------
   1 | >>> FROM jammsen/base:wine-stable-debian-bullseye
   2 |
   3 |     LABEL maintainer="Sebastian Schmidt"
--------------------
ERROR: failed to solve: jammsen/base:wine-stable-debian-bullseye: failed to resolve source metadata for docker.io/jammsen/base:wine-stable-debian-bullseye: docker.io/jammsen/base:wine-stable-debian-bullseye: not found
```

### Desired behavior

It seems that `jammsen/base:wine-stable-debian-bullseye` no longer exists. Browsing around the [docker registry](https://hub.docker.com/r/jammsen/base/tags), maybe `jammsen/base:wine-stable-debian-bookworm` is a suitable replacement?

### To Reproduce

1. Run `./docker-build.sh` or manually do a docker build
2. Get error

### Software setup

- OS: Ubuntu Server 18
- Docker: version 27.4.1

### Hardware setup

N/A

### Additional context

Seems like this could be an easy 1 line fix. Wanted to report here in case anyone else trying to use this repo encounters a similar error. Using `jammsen/base:wine-stable-debian-bookworm` successfully built the image.

**Comment by jammsen** [comment]
Hello @JamesComo44 - Thats because its the replacement for it, did you try to do a git pull to get the newest changes?

**Comment by JamesComo44** [comment]
I checked out the repo yesterday (12/27/24). However, on master I still see the Dockerfile using `jammsen/base:wine-stable-debian-bullseye` which no longer exists. 
https://github.com/jammsen/docker-the-forest-dedicated-server/blob/46190e3bccb5fc656711efcc1ab40bbc1ecc2647/Dockerfile#L1

**Comment by jammsen** [comment]
> I checked out the repo yesterday (12/27/24). However, on master I still see the Dockerfile using `jammsen/base:wine-stable-debian-bullseye` which no longer exists.
> 
> https://github.com/jammsen/docker-the-forest-dedicated-server/blob/46190e3bccb5fc656711efcc1ab40bbc1ecc2647/Dockerfile#L1

Oh yeah, sorry my bad, i moved on from bullseye, because of to many unresolved CVEs, im gonna update the code and build a new image. I guess i just missed this here but covered SOTF's base-image 😄 thanks for reporting this!

**Comment by jammsen** [comment]
Hey @JamesComo44 
Changed a few things and added the new base-image and tested it locally. See https://github.com/jammsen/docker-the-forest-dedicated-server/commit/e1f035946ac29202bf2c7dec3fcdace0f51ece52 and https://hub.docker.com/r/jammsen/the-forest-dedicated-server/tags

Feel free to test it out 👍

**Comment by JamesComo44** [comment]
This worked! I was able to get a server running using `docker compose up -d`. This is a big victory after many hours of struggling. You are awesome for updating the repo and being so responsive to my open issue. Thank you so much.

**Comment by jammsen** [comment]
Hey @JamesComo44 
Sorry it took so long, wanted to do extensive testing with changing Base-Images. 
Also no problem at all, i had time and i wanted to program anyways 😄 

Please feel free to join the Discord

**Comment by jammsen** [comment]
@JamesComo44 - I preparing fordrastically change the base-image and how the image works. I currently worked this entire day on SOTF see here: https://discord.com/channels/532141442731212810/1201632296395096218/1325180490193571974

Feel free to test this too, this change will also happen to the TF image. This will solve a lot of steamcmd errors, QNAP/SYNOLOGY/NAS and user-privilege problems.

**Comment by jammsen** [comment]
Hey @JamesComo44 - New image is live, no need for base images anymore, im using a popular steamcmd image now and doing multi-stage builds to build the gameserver image, should be way better then before.

**Comment by JamesComo44** [comment]
This is great! I haven't had an opportunity to test yet, but I will test out the new image soon.

Have not tried SOTF yet, but once we beat the first game I'm sure I'll setup a server for SOTF. Now I know where to look for that docker image. If any issues arise, I'll be sure to properly diagnose and open a bug report on that repo if necessary... but I feel confident it's all going to work.

Seriously, thanks again for all your hard work. You are a beacon of light in the software engineering world.

**Comment by jammsen** [comment]
> This is great! I haven't had an opportunity to test yet, but I will test out the new image soon.
> 
> Have not tried SOTF yet, but once we beat the first game I'm sure I'll setup a server for SOTF. Now I know where to look for that docker image. If any issues arise, I'll be sure to properly diagnose and open a bug report on that repo if necessary... but I feel confident it's all going to work.

Let me know if something isnt working and have fun gaming 😎 🥳 

> Seriously, thanks again for all your hard work. You are a beacon of light in the software engineering world.

😊 Thank you!
