### ISSUE TITLE
Docker image does not build anymore

### ISSUE THREAD

**Issue by Freekers** [jammsen/docker-the-forest-dedicated-server#8]
I'm not sure if this is maintained anymore, but I'm trying to create an updated version of the Docker image because of possible security vulnerabilities in the base image, as the current one is over a year old.

However, I'm unable to build the Docker image, probably due to some packages being renamed or have shifted to different repositories:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
winehq-stable : Depends: wine-stable (= 6.0.0~bionic-1)
[91mE[0m
[91m: Unable to correct problems, you have held broken packages.
[0m
Removing intermediate container aaf37a4c5f5d
The command '/bin/sh -c dpkg --add-architecture i386 && apt-get update && apt-get install -y wget software-properties-common supervisor apt-transport-https xvfb winbind cabextract && wget https://dl.winehq.org/wine-builds/winehq.key && apt-key add winehq.key && rm winehq.key && apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/ && apt-get update && apt-get install -y winehq-stable && wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && chmod +x ./winetricks && WINEDLLOVERRIDES="mscoree,mshtml=" wineboot -u && wineserver -w && ./winetricks -q winhttp wsh57 vcrun6sp6' returned a non-zero code: 100
```

[I made an attempt to fix the above in my own fork ](https://github.com/Freekers/docker-the-forest-dedicated-server)and was able to get the image to build, but the server refuses to start.

It would be nice if we could rebuild the image, [especially since Docker has revised it's retention policy and has stated it will remove stale/old images from Docker Hub.](https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/)

Thank you.

**Comment by ghost** [comment]
Would like update on this as well

**Comment by jammsen** [comment]
First of let me say im so sorry, but i never got any notification on open issues for this. 

Of course i maintain this image if there is any problem, i just never got any emails from github, so i didnt know there where problems. I would love to take a look at this.

I also can do a re-build of my base-images

**Comment by jammsen** [comment]
After looking into the build problem you described and trying it myself, this image and my the base-images ( https://github.com/jammsen/docker-base-images ) need to get a big upgrade. 

The problem is that wine again changed this up. This time you need libfaudio0, which is of course not included :). Thats why the build dont work, more on the topic you can find here: https://askubuntu.com/questions/1100351/broken-packages-fix-problem-for-wine/1205535#1205535

Im working on a fix.

**Comment by jammsen** [comment]
So im done fixning.
I have completely rebuild the image, you guys can try it out and do if you like some extended testing. My base tests worked. 
Also a benefit from switchting, the image is now down to about 910MB from 2,3-2,5GB.

**Comment by Freekers** [comment]
Thanks for fixing. I pulled the image and everything seems to work like it should. Good job on the image size reduction, that's some serious optimization & space savings :)
Thank you!
